version: '3'
services:
  db:
    image: postgres
    container_name: postgresql_app
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app_container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
