# Generated by Django 4.2.5 on 2023-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvserv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='description',
            field=models.CharField(default='none', max_length=100, verbose_name='description'),
        ),
    ]
