# Generated by Django 4.2.5 on 2023-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvserv', '0002_csvmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
    ]
