# Generated by Django 4.2.5 on 2023-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvserv', '0004_rename_description_csvmodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='file_name',
            field=models.CharField(max_length=100, verbose_name='file_name'),
        ),
    ]
